"""Render the docs screenshot set.

    python docs-screenshots/generate.py                  # -> docs-screenshots/out/
    python docs-screenshots/generate.py --out docs/images # overwrite the live library
    python docs-screenshots/generate.py --only Coordinator

Writes to a staging directory by default; pointing it at docs/images/ is an
explicit choice.
"""

import argparse
import collections
import pathlib
import sys
import time
from unittest.mock import Mock

import shim
from shim import REPO_ROOT, ScreenshotComplete, ScreenshotRenderer, screen_overrides

import fixture
import manifest

from PIL import Image

from seedsigner.controller import Controller
from seedsigner.gui.renderer import Renderer
from seedsigner.models.settings import Settings
from seedsigner.models.settings_definition import SettingsConstants


def build_renderer(out_dir: pathlib.Path) -> ScreenshotRenderer:
    """Swap the hardware Renderer for the file-writing one, app-wide."""
    ScreenshotRenderer.configure_instance()
    renderer = ScreenshotRenderer.get_instance()
    renderer.set_screenshot_path(str(out_dir))

    Renderer.configure_instance = Mock()
    Renderer.get_instance = Mock(return_value=renderer)
    return renderer


def render(shot, renderer) -> None:
    with renderer.lock:
        renderer.set_screenshot_filename(shot.filename)

    # Reset first so each shot is independent of the ones before it.
    manifest.reset_state()
    if shot.run_before:
        shot.run_before()
    toast_thread = shot.toast() if shot.toast else None
    try:
        with screen_overrides(shot.screen_kwargs, shot.screen_mutate):
            shot.View_cls(**shot.view_kwargs).run()
    except ScreenshotComplete:
        # The screen rendered. A toast then draws on top of that same buffer and
        # saves again, so the file ends up with the notification overlaid.
        if toast_thread is not None:
            controller = Controller.get_instance()
            controller.activate_toast(toast_thread)
            while controller.toast_notification_thread.is_alive():
                time.sleep(0.01)
    finally:
        if toast_thread is not None and toast_thread.is_alive():
            toast_thread.stop()
            toast_thread.join()
        if shot.run_after:
            shot.run_after()


def verify(out_dir: pathlib.Path, shots) -> list[str]:
    """Every shot produced a file, and every file is a 240x240 PNG."""
    problems = []
    for shot in shots:
        path = out_dir / shot.filename
        if not path.is_file():
            problems.append(f"{shot.filename}: not written")
            continue
        with Image.open(path) as img:
            if img.size != shim.CANVAS_SIZE:
                problems.append(f"{shot.filename}: {img.size[0]}x{img.size[1]}, expected 240x240")
    return problems


def census() -> int:
    """Reconcile the live library against GENERATED / PRESERVED / RETIRED.

    Every file in docs/images/ must be accounted for by exactly one bucket, and
    every bucket entry must correspond to a real file. Anything left over is a
    manifest gap, which is how a screen quietly goes missing.
    """
    images_dir = REPO_ROOT / "docs" / "images"
    on_disk = {p.name for p in images_dir.iterdir() if p.is_file()}
    generated = {s.filename for s in manifest.SHOTS}
    preserved = set(manifest.PRESERVED)
    retired = set(manifest.RETIRED)

    print(f"docs/images/ on disk     {len(on_disk)}")
    print(f"  generated by manifest  {len(generated)}")
    print(f"  preserved as-is        {len(preserved)}")
    print(f"  retired (to delete)    {len(retired)}")

    overlaps = [
        ("generated & preserved", generated & preserved),
        ("generated & retired", generated & retired),
        ("preserved & retired", preserved & retired),
    ]
    unaccounted = on_disk - generated - preserved - retired
    new_files = generated - on_disk
    # Retired files being gone is the goal, so only preserved files may go missing.
    phantom = preserved - on_disk
    not_yet_retired = retired & on_disk - {
        n for n in retired if n.lower() in {g.lower() for g in generated}
    }

    problems = False
    for label, names in overlaps:
        if names:
            problems = True
            print(f"\nIn two buckets ({label}):")
            for n in sorted(names):
                print(f"  - {n}")
    if unaccounted:
        problems = True
        print(f"\nOn disk but in no bucket ({len(unaccounted)}):")
        for n in sorted(unaccounted):
            print(f"  - {n}")
    if phantom:
        problems = True
        print(f"\nPreserved but not on disk ({len(phantom)}):")
        for n in sorted(phantom):
            print(f"  - {n}")
    if not_yet_retired:
        print(f"\nStill to retire ({len(not_yet_retired)}) -- run --retire:")
        for n in sorted(not_yet_retired):
            print(f"  ~ {n}")
    if new_files:
        print(f"\nNew files the manifest adds ({len(new_files)}):")
        for n in sorted(new_files):
            print(f"  + {n}")

    if not problems:
        print("\nEvery file accounted for.")
    return 1 if problems else 0


def links() -> int:
    """Every image reference resolves, and every image file is referenced.

    The second half is the one that rots: the audit found 51% of the library
    orphaned, which is invisible unless something counts it.
    """
    import re

    docs = REPO_ROOT / "docs"
    images = {p.name for p in (docs / "images").iterdir() if p.is_file()}
    refs = collections.defaultdict(set)

    for path in list(docs.rglob("*.md")) + list(docs.rglob("*.html")):
        if "images" in path.parts:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r'images/([^\s")\']+\.(?:png|jpg|jpeg))', text):
            refs[m.group(1)].add(str(path.relative_to(docs)).replace("\\", "/"))

    broken = {n: v for n, v in refs.items() if n not in images}
    # contribute/docs.md documents the image syntax; its example is not a real ref.
    broken.pop("filename.png", None)
    orphans = images - set(refs)

    print(f"files={len(images)} referenced={len(set(refs) & images)} "
          f"orphans={len(orphans)} broken={len(broken)}")
    for name, pages in sorted(broken.items()):
        print(f"  BROKEN {name}  <- {', '.join(sorted(pages))}")
    for name in sorted(orphans):
        print(f"  orphan {name}")
    return 1 if broken or orphans else 0


def retire() -> int:
    """Delete the RETIRED files from docs/images/.

    Separate from rendering because it is the one destructive step. Every entry
    was verified against the audit's duplicate/misnamed findings, and all of them
    are git-tracked, so this is recoverable.
    """
    images_dir = REPO_ROOT / "docs" / "images"

    # Two RETIRED entries differ from a GENERATED filename only by letter case
    # (SelectVIew vs SelectView). Windows and macOS treat those as one file, so
    # deleting the old name would delete the newly rendered content. Skip them and
    # let the render overwrite in place.
    generated_lower = {s.filename.lower() for s in manifest.SHOTS}

    removed, absent, skipped = [], [], []
    for name, (replacement, reason) in sorted(manifest.RETIRED.items()):
        path = images_dir / name
        if name.lower() in generated_lower:
            skipped.append(f"{name} -> {replacement} (case-only rename)")
            continue
        if not path.exists():
            absent.append(name)
            continue
        path.unlink()
        target = f" -> {replacement}" if replacement else ""
        removed.append(f"{name}{target}  ({reason})")

    for line in removed:
        print(f"  deleted  {line}")
    for name in absent:
        print(f"  absent   {name}")
    for line in skipped:
        print(f"  skipped  {line}")
    print(f"\nRetired {len(removed)} file(s), skipped {len(skipped)} case-only rename(s).")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="docs-screenshots/out",
                        help="output directory, relative to the repo root")
    parser.add_argument("--only", default=None,
                        help="render only shots whose filename contains this substring")
    parser.add_argument("--census", action="store_true",
                        help="reconcile docs/images against the manifest and exit")
    parser.add_argument("--retire", action="store_true",
                        help="delete the RETIRED files from docs/images and exit")
    parser.add_argument("--links", action="store_true",
                        help="check every image reference resolves and every file is used")
    parser.add_argument("--locale", default="en")
    args = parser.parse_args()

    duplicates = [f for f, n in collections.Counter(
        s.filename for s in manifest.SHOTS).items() if n > 1]
    if duplicates:
        print("Duplicate filenames in the manifest:", file=sys.stderr)
        for f in sorted(duplicates):
            print(f"  - {f}", file=sys.stderr)
        return 1

    if args.census:
        return census()
    if args.links:
        return links()
    if args.retire:
        return retire()

    out_dir = (REPO_ROOT / args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    shots = [s for s in manifest.SHOTS
             if not args.only or args.only.lower() in s.filename.lower()]
    if not shots:
        print(f"No shots match --only {args.only!r}", file=sys.stderr)
        return 1

    renderer = build_renderer(out_dir)
    shim.install_run_screen_patch()

    Controller.reset_instance()
    controller = Controller.get_instance()
    Settings.get_instance().set_value(SettingsConstants.SETTING__LOCALE, args.locale)
    manifest.setup(controller)

    print(fixture.summary())
    print(f"\nRendering {len(shots)} shot(s) -> {out_dir}\n")

    failures = []
    for shot in shots:
        try:
            render(shot, renderer)
            print(f"  ok    {shot.filename}")
        except Exception as exc:  # keep going; report everything at the end
            failures.append(f"{shot.filename}: {type(exc).__name__}: {exc}")
            print(f"  FAIL  {shot.filename}  ({type(exc).__name__}: {exc})")

    problems = failures + verify(out_dir, [s for s in shots
                                           if not any(s.filename in f for f in failures)])
    if problems:
        print("\nProblems:")
        for p in problems:
            print(f"  - {p}")
        return 1

    print(f"\nAll {len(shots)} shot(s) rendered and verified at 240x240.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
